coverage:
  range: 50..70
  round: down
  precision: 0
  ignore:
    # ignore all generated files, as we do not control those
    - zerorobot/server/types/.*
    - zerorobot/server/app.py
    - zerorobot/server/blueprints_api.py
    - zerorobot/server/templates_api.py
    - zerorobot/server/services_api.py
    - zerorobot/server/robot_api.py
    - JumpScale9Zrobot/clients/zerorobot/client/.*