# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

"""
Auto-generated class for Metrics
"""
from .Metricscpu import Metricscpu
from .Metricsmemory import Metricsmemory

from . import client_support


class Metrics(object):
    """
    auto-generated. don't touch.
    """

    @staticmethod
    def create(**kwargs):
        """
        :type cpu: Metricscpu
        :type memory: Metricsmemory
        :type nr_services: int
        :rtype: Metrics
        """

        return Metrics(**kwargs)

    def __init__(self, json=None, **kwargs):
        if json is None and not kwargs:
            raise ValueError('No data or kwargs present')

        class_name = 'Metrics'
        data = json or kwargs

        # set attributes
        data_types = [Metricscpu]
        self.cpu = client_support.set_property('cpu', data, data_types, False, [], False, True, class_name)
        data_types = [Metricsmemory]
        self.memory = client_support.set_property('memory', data, data_types, False, [], False, True, class_name)
        data_types = [int]
        self.nr_services = client_support.set_property(
            'nr_services', data, data_types, False, [], False, True, class_name)

    def __str__(self):
        return self.as_json(indent=4)

    def as_json(self, indent=0):
        return client_support.to_json(self, indent=indent)

    def as_dict(self):
        return client_support.to_dict(self)
