# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.
from .Metrics import Metrics
from .RobotInfo import RobotInfo
from .WebHook import WebHook
from .unhandled_api_error import UnhandledAPIError
from .unmarshall_error import UnmarshallError


class RobotService:
    def __init__(self, client):
        self.client = client

    def GetRobotInfo(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /robot/info
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/robot/info"
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return RobotInfo(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def GetMetrics(self, headers=None, query_params=None, content_type="application/json"):
        """
        It is method for GET /robot/metrics
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/robot/metrics"
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                return Metrics(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def DeleteWebHook(self, id, headers=None, query_params=None, content_type="application/json"):
        """
        delete a web hook configuration
        It is method for DELETE /robot/webhooks/{id}
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/robot/webhooks/" + id
        return self.client.delete(uri, None, headers, query_params, content_type)

    def ListWebHooks(self, headers=None, query_params=None, content_type="application/json"):
        """
        List all configured web hooks
        It is method for GET /robot/webhooks
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/robot/webhooks"
        resp = self.client.get(uri, None, headers, query_params, content_type)
        try:
            if resp.status_code == 200:
                resps = []
                for elem in resp.json():
                    resps.append(WebHook(elem))
                return resps, resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)

    def AddWebHook(self, data, headers=None, query_params=None, content_type="application/json"):
        """
        Add a new web hook configuration
        It is method for POST /robot/webhooks
        """
        if query_params is None:
            query_params = {}

        uri = self.client.base_url + "/robot/webhooks"
        resp = self.client.post(uri, data, headers, query_params, content_type)
        try:
            if resp.status_code == 201:
                return WebHook(resp.json()), resp

            message = 'unknown status code={}'.format(resp.status_code)
            raise UnhandledAPIError(response=resp, code=resp.status_code,
                                    message=message)
        except ValueError as msg:
            raise UnmarshallError(resp, msg)
        except UnhandledAPIError as uae:
            raise uae
        except Exception as e:
            raise UnmarshallError(resp, e.message)
