#!/usr/bin/env python3

import click

from zerorobot.cli.server import server
from zerorobot.cli.robot import robot
from zerorobot.cli.service import service
from zerorobot.cli.template import template
from zerorobot.cli.task import task


@click.group()
def entry_point():
    pass

entry_point.add_command(server)
entry_point.add_command(robot)
entry_point.add_command(service)
entry_point.add_command(template)
entry_point.add_command(task)


if __name__ == "__main__":
    entry_point()
