# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.


class PassThroughClientService:
    def __init__(self, http_client):
        self._http_client = http_client

    def set_zrobotsecret_header(self, val):
        """" Set header ZrobotSecret to '<val>'"""
        self._http_client.set_header('Zrobot', val)  # for backward compatibility with 0.6.x
        return self._http_client.set_header('ZrobotSecret', val)
