# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
from . import handlers


robot_api = Blueprint('robot_api', __name__)


@robot_api.route('/robot/info', methods=['GET'])
def GetRobotInfo():
    """
    It is handler for GET /robot/info
    """
    return handlers.GetRobotInfoHandler()


@robot_api.route('/robot/metrics', methods=['GET'])
def GetMetrics():
    """
    It is handler for GET /robot/metrics
    """
    return handlers.GetMetricsHandler()
