# DO NOT EDIT THIS FILE. This file will be overwritten when re-running go-raml.

from flask import Blueprint
from . import handlers


templates_api = Blueprint('templates_api', __name__)


@templates_api.route('/templates', methods=['GET'])
def ListTemplates():
    """
    List all the templates available to the ZeroRobot
    It is handler for GET /templates
    """
    return handlers.ListTemplatesHandler()


@templates_api.route('/templates', methods=['POST'])
def AddTemplateRepo():
    """
    Clone a template repository and make the templates available to the ZeroRobot
    It is handler for POST /templates
    """
    return handlers.AddTemplateRepoHandler()
