[startup."zrobot-vol"]
name = "bash"
running_delay = -1

[startup."zrobot-vol".args]
script = """
set -e
ROOT=/var/cache
btrfs subvol create ${ROOT}/zrobot || true
for dir in ssh data config jsconfig; do
    mkdir -p ${ROOT}/zrobot/${dir}
done
"""

[startup.zrobot]
name = "corex.create-sync"
tags = ["zrobot"]
protected = true
after = ["zrobot-vol"]

[startup.zrobot.args]
root = "https://hub.grid.tf/tf-autobuilder/threefoldtech-0-robot-autostart-development.flist"
name = "zrobot"
privileged = false
host_network = false

[startup.zrobot.args.env]
HOME = "/root"
LC_ALL = "C.UTF-8"
LANG = "C.UTF-8"

[[startup.zrobot.args.nics]]
type = "default"

[startup.zrobot.args."not(zerotier)|port"]
"6600"=6600

[startup.zrobot.args."zerotier|port"]
"zt*:6600"=6600

#mount all zrobot essential directories
#on persisted cache
[startup.zrobot.args.mount]
"/var/cache/zrobot/ssh" = "/root/.ssh"
"/var/cache/zrobot/data" = "/opt/var/data/zrobot/zrobot_data"
"/var/cache/zrobot/config" = "/opt/code/local/stdorg/config"
"/var/cache/zrobot/jsconfig" = "/root/jumpscale/cfg"
"/var/run/redis.sock" = "/tmp/redis.sock"
